<?xml version="1.0" encoding="utf-8"?><Database Name="CinemaDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-O0E4MOU;Initial Catalog=CinemaDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CinemaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CinemaMovie" Member="CinemaMovies">
    <Type Name="CinemaMovie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>